### ISSUE TITLE
Multiple "Warning: SSL error ignored" displayed during conversion from source webpage to PDF (very specific case)

### ISSUE THREAD

**Issue by stringbeans** [wkhtmltopdf/wkhtmltopdf#2103]
Hi there,

I'm running wkhtmltopdf on "https://app.edvisor.io/en" specifically and here is my output:

```
/usr/local/bin/wkhtmltopdf --no-stop-slow-scripts --lowquality --viewport-size 1280x1024 'https://app.edvisor.io/en' '/Users/riverstyx/Desktop/jakarta.pdf'
Loading pages (1/6)
Warning: SSL error ignored                                        
Warning: SSL error ignored                                        
Warning: SSL error ignored                                        
Warning: SSL error ignored
Warning: SSL error ignored
Warning: SSL error ignored
Warning: Failed to load https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.5.2/underscore-min.js (ignore)
Warning: Failed to load https://cdnjs.cloudflare.com/ajax/libs/backbone.js/1.1.0/backbone-min.js (ignore)
Warning: SSL error ignored                                        
Counting pages (2/6)                                               
Warning: Received createRequest signal on a disposed ResourceObject's NetworkAccessManager. This migth be an indication of an iframe taking to long to load.
Resolving links (4/6)
Loading headers and footers (5/6)                                           
Printing pages (6/6)
Done                                                                      
Exit with code 1 due to network error: UnknownNetworkError
```

However this output is inconsistent and seems to change slightly each time I run the command. I've also found that if I remove all references to CDNJS specifically it works fine. 

I thought at first that maybe the problem was specific to CDNJS however when I run the command on other sites that also utilize CDNJS they process fine. 

Any ideas as to why this would be occurring?

**Comment by warren5236** [comment]
Thanks for the great software!

I'm getting the same error.  This is what `wget` returns for me.

    wget https://server.com
    --2015-02-04 09:27:45--  https://server.com/
    Resolving server.com (server.com)... 205.145.140.81
    Connecting to server.com (server.com)|205.145.140.81|:443... connected.
    ERROR: cannot verify server.com's certificate, issued by `/C=--/ST=SomeState/L=SomeCity/O=SomeOrganization/OU=SomeOrganizationalUnit/CN=hostname/emailAddress=root@hostname':
      Self-signed certificate encountered.
        ERROR: certificate common name `hostname' doesn't match requested host name `server.com'.
    To connect to server.com insecurely, use `--no-check-certificate'.


The site's certificate works fine in Chrome/Firefox/IE/etc.

**Comment by evxzibit** [comment]
Good day,

I am getting the same scenario described above (Exit with code 1 due to network error: UnknownNetworkError).

Did you guys get around this issue?

**Comment by phil3209** [comment]
I am with the same problem, and it works well with wget, but in my php laravel project it comes the warning messages Failed to load https: **********. Can anyone help? thx

**Comment by Tomsgu** [comment]
This should be resolved in 0.12.5.

**Comment by DarkSide666** [comment]
Problem still persists in `0.12.5`

```
wkhtmltopdf.exe --print-media-type --javascript-delay 5000 --no-stop-slow-scripts https://mysite.loc/tmp/report.html C:\wamp\www\tmp/preview.pdf
Loading pages (1/6)
Warning: SSL error ignored
Warning: SSL error ignored
Warning: SSL error ignored
Warning: SSL error ignored
Warning: SSL error ignored
Warning: SSL error ignored
QFont::setPixelSize: Pixel size <= 0 (0)=============>       ] 87%
Counting pages (2/6)
QFont::setPixelSize: Pixel size <= 0 (0)=====================] Object 1 of 1
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done
```
It's localhost site with SSL enabled and that page contains JS loaded from other sites.
