### ISSUE TITLE
Exit with code 1 due to network error: UnknownContentError while converting html to pdf

### ISSUE THREAD

**Issue by no1stunna** [wkhtmltopdf/wkhtmltopdf#2187]
There is html file:

https://gist.github.com/no1stunna/36637bac02569ad6744e

When i do 

```
    wkhtmltopdf issue.html test.pdf
```

There is an error: 

```
Loading pages (1/6)
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done
Exit with code 1 due to network error: UnknownContentError
```

Most of the time its working well. But for some generated google urls like this one it throws such an error. 

**Thanks a lot.**

**Comment by B1nTree** [comment]
Bumping having this same issue

**Comment by kenorb** [comment]
The same here.

     $ wkhtmltopdf page.html page.pdf
    Loading pages (1/6)
    Warning: Failed to load file://connect.facebook.net/en_US/sdk.js (ignore)
    Warning: SSL error ignored                                        
    Counting pages (2/6)                                               
    Resolving links (4/6)                                                       
    Loading headers and footers (5/6)                                           
    Printing pages (6/6)
    Done                                                                        
Exit with code 1 due to network error: UnknownContentError

**Comment by kenorb** [comment]
See: [QNetworkReply Class](http://doc.qt.io/qt-4.8/qnetworkreply.html#NetworkError-enum)

> QNetworkReply::UnknownContentError	299	an unknown error related to the remote content was detected

In #1948 we can read:

> It looks like you are trying to load a dynamic resource which is not found (see [explanation](http://doc.qt.io/qt-4.8/qnetworkreply.html#NetworkError-enum))  -- you might want to see what it is.

However it doesn't solve the problem, because there is no way to ignore such error and continue. Currently it prevents generation of the output file.

**Comment by team4music** [comment]
Same problem here =(

**Comment by brafdlog** [comment]
Same here :(

**Comment by sashamjolnir** [comment]
Same problem :calendar:

**Comment by kai789** [comment]
I found a fix for my problem but as I narrowed down the simplest html to cause the problem, the rendering engine seems rather unreliable. My fix is to adjust the css "page-break-before: always;" location. The error would only occur in a very specific set of conditions. But as I narrowed it down, the html which reliably reproduces the problem seems rather general.

Simple example to reproduce it:
1000 of these: <div>Test</div>
(maybe the 16-18 page mark is hitting the problem)
A blank header and a blank footer.
All static files hosted on a website running on localhost (it is fine when pages are local files).

Example 2:
<style type='text/css'>div { page-break-before: always; }</style>
20 of these: <div>Test</div>

I found it by doing this: delete half of html/css file, see if problem is fixed, delete half of problem section, see if problem is fixed, repeat. Until I had the simplest offending example.

Related: https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2083

I am using 0.12.2.4. I also upgraded to 0.12.3.1 and still hit the problem.

0.13.0 does not have the problem.

**Comment by cm8** [comment]
I hit this error for a [single page]() _without_ any header or footer and _without_ javascript running.

To debug this problem try running the conversion with **--no-images**.

In my case the conversion ran fine without images loaded. I saved the file locally to find out which image was offending. To test with that local copy do not forget to set e.g. <base href=".."/> in the <head> section of the html appropiately.

If the document is large, use grep -A2 "<img" to find urls to check. Use wget on these urls and inspect the **content**.

For my test case this yielded [a valid resource (code 200) on archive.org, that was not an image (hence the "unknown content error" from qt)](https://web.archive.org/web/20160306001714im_/https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/75px-Namibia.SamNujoma.01.jpg).

Arguably, this is either a bug of archive.org or commons - we can't tell.

This should not have been archived as an image at archive.org, regardless of whether the resource was delivered with a 200 or any other http status code to commons, since in fact it's not a valid image. On the other end commons should not have delivered what is in fact an error message as a 200 with html content, when a jpg mime was requested.

-> "unknown content error" from QT is indeed very descriptive for the problem in this case.

After a review I can "ignore" this problem, since the pdf in question renders fine without it.  However I do want to ignore non-zero return status from wkhtmltopdf in a batch invocation (to find and break a script on more serious errors).

The default setting **--load-media-error-handling ignore** should lead to a zero status code returned, _if_ the "unknown content error" results from QT trying to load the src= in html <img> tags (or, more generally, if a resource with an image/* mime type or an image file ending was to be loaded).

**Comment by bronson** [comment]
Yep, I'm getting this error consistently with 0.12.1 and 0.12.3:

```
$ wkhtmltopdf http://prop.gisweb.com/print/geosearch/m/tCentralFlorida out.pdf
Loading pages (1/6)
QFont::setPixelSize: Pixel size <= 0 (0)                     ] 48%
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done
Exit with code 1 due to network error: UnknownContentError
```

So I upgraded to 0.13.0-alpha-7b36694 and I'm getting:

```
wkhtmltopdf http://prop.gisweb.com/print/geosearch/m/tCentralFlorida out.pdf
Loading page (1/2)
Printing pages (2/2)
Done
Exit with code 1 due to network error: InternalServerError
```

Sigh.  I guess I'll hack my app to ignore error 1...  Hoping someone finds a better solution.

**Comment by rk** [comment]
I've had this error happen when using the `--post key value` param on a command that normally works (v0.12.3).

```
Loading pages (1/6)
content-type missing in HTTP POST, defaulting to application/x-www-form-urlencoded. Use QNetworkRequest::setHeader() to fix this problem.
content-type missing in HTTP POST, defaulting to application/x-www-form-urlencoded. Use QNetworkRequest::setHeader() to fix this problem.
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done
Exit with code 1 due to network error: UnknownContentError
```

I was able to confirm the exact same request worked with jQuery `$.post()`, for both the cover page and the content. I have 1 external linked resource (a logo on the cover page) referenced by HTTP, so there shouldn't be a problem there.

**Comment by hbarrington** [comment]
We just started receiving this error as well. We're still trying to debug the root cause in our case but passing the `--no-images` parameter seems to resolve it for us as well. We're not sure why.

**Comment by brafdlog** [comment]
This happened to me when there was a missing image in the page. One the
image was removed from the page it was fixed.

**Comment by omrqs** [comment]
This error occurs when url are defined as //url... in place of https://url....
Keep the protocol. 
wkhtmltopdf try find double slash as local path...

Solved for me.

**Comment by seanthebean** [comment]
Anyone know of any way to diagnose which resource is causing the problem? (Using the process of elimination can be very tedious/difficult if the PDF includes a lot of resources, or they're being programmatically included.)

**Comment by Glepooek** [comment]
was this problem solved?
![image](https://user-images.githubusercontent.com/10616673/29605496-a6715450-881d-11e7-8a71-7e08e2ef7ed3.png)

**Comment by DionataNunesGarcia** [comment]
I have the same error, when it reaches 18 or more pages and including the footer and the header with html with URL, returns this error, and with menas pages it works normally, but until now I could not solve the problem, I give a URL to the footer and the header always returns the error "Exit with code 1 due to network error: UnknownContentError".
Does anyone already know how to fix it? I already tried everything I researched.

**Comment by sbont** [comment]
@DionataNunesGarcia me too, large documents seem to cause this error too.
Have you found a way to solve this issue?

**Comment by gokulk16** [comment]
Same error. there should be an option created for handling this `ContentNotFoundError`. 
Also in most cases, those are images.

**Comment by alloylab** [comment]
What flavor of linux are y'all running? What version of wkhtmltopdf? Is a patched QT version?
Is the certificate chain valid for https url?

Do you have openssl & ca-certificates packaged installed?

**Comment by alloylab** [comment]
is this still an issue on 0.12.5?

**Comment by Killium** [comment]
@alloylab I was going to ask. Glad to see that some people want to see this issue out.

**Comment by Tomsgu** [comment]
SSL issues were fixed in 0.12.5. It should be also easier to debug the problem, when ContentNotFoundError will appear.

**Comment by Tomsgu** [comment]
Closing as there is no response. Please feel free to open a new issue with a complete example if you have some of the problems from this issue.

**Comment by rainabba** [comment]
I'm seeing this with 12.3 on WSL/Ubuntu 18.04, Windows 1803. When I pull these pages in browser, everything is 200 or 304 as expected.

**Comment by singhravi1** [comment]
Got this error when i tried to create a 70 page pdf. Any possible solution?

**Comment by rainabba** [comment]
For me, the issue is resolved with 12.4

**Comment by singhravi1** [comment]
i'm using 0.12.5 version. But still having this issue. Any idea?

**Comment by theredled** [comment]
Same

**Comment by rafaeljusto** [comment]
This PR will probably solve this issue:
https://github.com/wkhtmltopdf/wkhtmltopdf/pull/4461
