### ISSUE TITLE
Images randomly not loading

### ISSUE THREAD

**Issue by mediatomcat** [wkhtmltopdf/wkhtmltopdf#3879]
Hi,

I am running wkhtmltopdf on a Centos 6 server with PHP 5.6.  The PHP page I am calling is a page made up of multiple images in a table format.  There is some code that will change the image of certain cells.  

The bizarre thing is that the PDF is often missing one or two random images from the document.  Each PDF document is a approximately 5 pages long.  The images that are missing are never the same and are not the dynamic ones either but are fixed.

I have made sure that the page reload fresh each time and that there is not caching taking place.  I have tried ob_cache to see if loading the page before any output helps.

The images in the PHP file are called using the full http:// path as i found using a basic path like /images/filesname.png did not work.  All the images are in gif format. 

Any help would be greatly appreciated.
![2018-04-16_0834](https://user-images.githubusercontent.com/2648702/38795835-64f7d27c-4151-11e8-9753-11d0da51861b.png)

**Comment by marisgithub** [comment]
Hi, I have similar issue. Have you solved it?

**Comment by marisgithub** [comment]
I fixed my issues, that was related to javascript that for bigger page loads messed things up. So I passed "disable-javascript" to wkhtmltopdf and it solved my issue.

**Comment by mediatomcat** [comment]
Unfortunately this does not resolve the issue.  I am wondering of there are simply too many images being loaded. Is there a better way to manage cache?

**Comment by alloylab** [comment]
Are you still having this issue in 0.12.5?

**Comment by mediatomcat** [comment]
1) I was producing multiple reports back to back, so added some code to put a 2 second delay between outputting the 2 reports.
2) I activated the cache folder and made sure that it was writeable on the server chmod 775 /yourfolder - and made sure that apache could write to it.  chown apache:apache

**Comment by jakenoble** [comment]
base64 encoding the images helped me when I had the same issue on 0.12.3
